version: "3.0"

services:
    
    mariadb:
        image: mariadb:latest
        container_name: mimariadb
        ports:
            - 3307:3306
        environment:
            - MARIADB_ROOT_PASSWORD=password
            - MARIADB_USER=usuario
            - MARIADB_PASSWORD=password
            - MARIADB_DATABASE=prueba
        volumes:
            - /home/ubuntu/environment/datos/mariadb:/var/lib/mysql
        
    mysql:
        image: mysql:latest
        container_name: mymysql
        ports:
            - 3308:3306
        environment:
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_USER=usuario
            - MYSQL_PASSWORD=password
            - MYSQL_DATABASE=prueba
        volumes:
            - /home/ubuntu/environment/datos/mysql:/var/lib/mysql
        
