kind: Service
apiVersion: v1

metadata:
  name: web-ejemplo-ansible
  labels:
    app: web-ejemplo-ansible
spec:
  ports:
    - name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: 8443-tcp
      protocol: TCP
      port: 8443
      targetPort: 8443
  selector:
    app: web-ejemplo-ansible
  type: ClusterIP
